# This file is part of cloudwatch-to-dataframe.
# https://github.com/kaija/cloudwatch_to_dataframe

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2020, kaija <kaija.chang@gmail.com>

language: python

python:
    - "2.7"
    - "3.4"
    - "pypy"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
